# Generated by Django 4.1.6 on 2023-02-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("priority", models.SmallIntegerField(default=3)),
                (
                    "fullImage",
                    models.ImageField(
                        help_text="Please upload image size of atleast: 1920p x 1080px",
                        upload_to="gallery",
                    ),
                ),
            ],
        ),
    ]
