# Generated by Django 4.1.6 on 2023-02-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="name",
        ),
        migrations.RemoveField(
            model_name="gallery",
            name="priority",
        ),
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.TextField(
                default="One or two statments describing the project in the image",
                help_text="This description would he displayed above the gallery image.",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="order",
            field=models.SmallIntegerField(default=10),
        ),
    ]
