# Generated by Django 4.1.6 on 2023-02-12 05:48

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0003_principle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.SmallIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("bio", models.CharField(max_length=150)),
                (
                    "self_image",
                    pictures.models.PictureField(
                        aspect_ratios=["4/5"],
                        breakpoints={
                            "l": 1024,
                            "m": 768,
                            "s": 640,
                            "xl": 1280,
                            "xs": 480,
                        },
                        container_width=1200,
                        file_types=["WEBP"],
                        grid_columns=12,
                        help_text="Please upload image size of atleast: 1920p x 1080px",
                        pixel_densities=[1, 2],
                        upload_to="gallery",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="gallery",
            name="fullImage",
            field=pictures.models.PictureField(
                aspect_ratios=["16/9"],
                breakpoints={"l": 1024, "m": 768, "s": 640, "xl": 1280, "xs": 480},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                help_text="Please upload image size of atleast: 1920p x 1080px",
                pixel_densities=[1, 2],
                upload_to="gallery",
            ),
        ),
    ]
