# Generated by Django 4.1.6 on 2023-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0003_principle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.SmallIntegerField()),
                ("name", models.CharField(max_length=120)),
                ("bio", models.CharField(max_length=150)),
                (
                    "self_image",
                    models.ImageField(
                        help_text="\n            Please convert your JPG/PNG/etc image to WEBP at cloudconvert.com or squoosh.app to ensure a smooth expreience for your users.\n\n            Also, please make sure the aspect ratio of the image is 4:5, similar to that of a Instagram post.\n        ",
                        upload_to="founder",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="gallery",
            name="fullImage",
            field=models.ImageField(
                help_text="\n            Please convert your JPG/PNG/etc image to WEBP at cloudconvert.com or squoosh.app to ensure a smooth expreience for your users.\n\n            Also, please make sure the image is of a minimum size of atleast 1920x1080px and 16:9 aspect ratio\n        ",
                upload_to="gallery",
            ),
        ),
    ]
