# Generated by Django 4.1.6 on 2023-02-12 05:51

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0004_founder_alter_gallery_fullimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="self_image",
            field=pictures.models.PictureField(
                aspect_ratios=["4/5"],
                breakpoints={"l": 1024, "m": 768, "s": 640, "xl": 1280, "xs": 480},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                help_text="Please upload image size of atleast: 1920p x 1080px",
                pixel_densities=[1, 2],
                upload_to="founder",
            ),
        ),
    ]
