# Generated by Django 4.1.7 on 2023-02-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0004_founder_alter_gallery_fullimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="order",
        ),
        migrations.AddField(
            model_name="gallery",
            name="index",
            field=models.SmallIntegerField(default=1),
        ),
    ]
