# Generated by Django 4.1.7 on 2023-02-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0005_remove_gallery_order_gallery_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="principle",
            name="border_bottom",
            field=models.BooleanField(default=False),
        ),
    ]
