# Generated by Django 4.1.6 on 2023-02-12 08:54

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0005_alter_founder_self_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="self_image",
            field=pictures.models.PictureField(
                aspect_ratios=["4/5"],
                breakpoints={"l": 1024, "m": 768, "s": 640, "xl": 1280, "xs": 480},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                help_text="Please upload either a WebP or AVIF image of 4:5 aspect ratio",
                pixel_densities=[1, 2],
                upload_to="founder",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="fullImage",
            field=models.ImageField(
                help_text="Please upload either a WebP or AVIF image of a minimum size of atleast 1920x1080px and 16:9 aspect ratio",
                upload_to="gallery",
            ),
        ),
    ]
