# Generated by Django 4.1.7 on 2023-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0006_principle_border_bottom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="order",
            field=models.SmallIntegerField(default=1),
        ),
    ]
