# Generated by Django 4.1.6 on 2023-02-12 09:02

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0006_alter_founder_self_image_alter_gallery_fullimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="self_image",
            field=pictures.models.PictureField(
                aspect_ratios=["4/5"],
                breakpoints={"l": 1024, "m": 768, "s": 640, "xl": 1280, "xs": 480},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                help_text="\n            Please convert your JPG/PNG/etc image to WEBP at cloudconvert.com to ensure a smooth expreience for your users.\n\n            Also, please make sure the aspect ratio of the image is 4:5, similar to that of a Instagram post.\n        ",
                pixel_densities=[1, 2],
                upload_to="founder",
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="fullImage",
            field=models.ImageField(
                help_text="\n            Please convert your JPG/PNG/etc image to WEBP at cloudconvert.com to ensure a smooth expreience for your users.\n\n            Also, please make sure the image is of a minimum size of atleast 1920x1080px and 16:9 aspect ratio\n        ",
                upload_to="gallery",
            ),
        ),
    ]
