# Generated by Django 4.1.6 on 2023-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0009_alter_founder_self_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founder",
            name="self_image",
            field=models.ImageField(
                help_text="\n            Please convert your JPG/PNG/etc image to WEBP at cloudconvert.com or squoosh.app to ensure a smooth expreience for your users.\n\n            Also, please make sure the aspect ratio of the image is 4:5, similar to that of a Instagram post.\n        ",
                upload_to="founder",
            ),
        ),
    ]
