# Generated by Django 4.1.7 on 2023-03-05 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0013_alter_seo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seo",
            options={"verbose_name": "SEO", "verbose_name_plural": "SEO"},
        ),
    ]
