# Generated by Django 4.1.7 on 2023-03-05 07:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0014_alter_seo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name_plural": "Gallery"},
        ),
    ]
