# Generated by Django 4.1.7 on 2023-03-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0016_partner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Please enter as follows: +91 9999999999",
                        max_length=13,
                    ),
                ),
                ("email", models.CharField(max_length=120)),
                ("address", models.TextField()),
                ("work_timings", models.TextField()),
            ],
            options={
                "verbose_name": "Contact Details",
                "verbose_name_plural": "Contact Details",
            },
        ),
    ]
