# Generated by Django 4.1.7 on 2023-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("v1", "0017_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(
                help_text="Please enter as follows: +91 9999999999", max_length=14
            ),
        ),
    ]
